# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='id',
        ),
        migrations.AlterField(
            model_name='listing',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='listing_photos', verbose_name='Listing Photo'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos', verbose_name='Profile Photo'),
        ),
    ]
